Updated challenges

diff --git a/kubernetes-new-relic-university/k8s-resources/check-kubernetes b/kubernetes-new-relic-university/k8s-resources/check-kubernetes
--- a/kubernetes-new-relic-university/k8s-resources/check-kubernetes
+++ b/kubernetes-new-relic-university/k8s-resources/check-kubernetes
@@ -1,3 +1,6 @@
 #!/bin/bash
 
 kubectl describe -n demo-app pod rabbit | grep Limits
+if [ $? -ne 0 ]; then
+    fail-message "Could not find resource limit on RabbitMQ pod. Please follow the instructions."
+fi
diff --git a/kubernetes-new-relic-university/nr-k8s-events/check-kubernetes b/kubernetes-new-relic-university/nr-k8s-events/check-kubernetes
--- a/kubernetes-new-relic-university/nr-k8s-events/check-kubernetes
+++ b/kubernetes-new-relic-university/nr-k8s-events/check-kubernetes
@@ -1,3 +1,6 @@
 #!/bin/bash
 
-kubectl get pods | grep nr-kube-events
+kubectl get pods | grep nri-kube-events
+if [ $? -ne 0 ]; then
+    fail-message "Could not find New Relic k8s events integration. Please follow the steps."
+fi
diff --git a/kubernetes-new-relic-university/nr-logs/check-kubernetes b/kubernetes-new-relic-university/nr-logs/check-kubernetes
--- a/kubernetes-new-relic-university/nr-logs/check-kubernetes
+++ b/kubernetes-new-relic-university/nr-logs/check-kubernetes
@@ -1,3 +1,6 @@
 #!/bin/bash
 
 kubectl get pods | grep newrelic-logging
+if [ $? -ne 0 ]; then
+    fail-message "Could not find New Relic Logging agent. Please follow the steps."
+fi
diff --git a/kubernetes-new-relic-university/nr-prometheus/check-kubernetes b/kubernetes-new-relic-university/nr-prometheus/check-kubernetes
--- a/kubernetes-new-relic-university/nr-prometheus/check-kubernetes
+++ b/kubernetes-new-relic-university/nr-prometheus/check-kubernetes
@@ -1,3 +1,6 @@
 #!/bin/bash
 
 kubectl get pods | grep nri-prometheus
+if [ $? -ne 0 ]; then
+    fail-message "Could not find the New Relic Prometheus integration. Please follow the steps."
+fi
